<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.hdl.boot</groupId>
        <artifactId>soar-framework</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>soar-spring-boot-starter-jpa</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>Database connection pool, multiple data sources, transactions, and Jpa extensions.</description>
    <url>https://github.com/long-hd/soar-be.git</url>

    <dependencies>
        <dependency>
            <groupId>com.hdl.boot</groupId>
            <artifactId>soar-common</artifactId>
        </dependency>

        <dependency>
            <groupId>com.hdl.boot</groupId>
            <artifactId>soar-spring-boot-starter-security</artifactId>
        </dependency>

        <!-- Spring -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>dynamic-datasource-spring-boot-starter</artifactId> <!-- Multiple Data Sources -->
        </dependency>

        <!-- Database -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <optional>true</optional>
        </dependency>

    </dependencies>
</project>