<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.hdl.boot</groupId>
        <artifactId>soar-framework</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>soar-spring-boot-starter-web</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>Web framework: global exception handling, API logging, data masking, error codes, etc.</description>
    <url>https://github.com/long-hd/soar-be.git</url>

    <dependencies>
        <dependency>
            <groupId>com.hdl.boot</groupId>
            <artifactId>soar-common</artifactId>
        </dependency>

        <!-- Web -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!-- Required dependencies for Spring Boot configuration -->
    </dependencies>

</project>